### PR TITLE
default generator installs/configs grunt deploy tasks

### LINKED ISSUE #28: Default generator could scaffold out grunt deployment tasks
For example:

https://github.com/tomwayson/web-appbuilder-tools-techniques-dev-summit-2015/tree/master/src/demo

As demonstrated here: http://video.esri.com/watch/4568/arcgis-web-appbuilder-development-tools-and-techniques

### PR DESCRIPTION
**Pull request by tomwayson**
add grunt tasks as dev deps to package.json
update to yeoman-generator v0.17 for gruntfile api
configure grunt tasks via gruntfile api
run npm install to install grunt tasks
minor change to theme tests b/c v0.17 changed how theme name is written to
manifest
updated instructions in readme to inlcude grunt tasks

resolves #28 

@gavinr please review and try out on your local system. Also take a look at the updated instructions in the README and verify that they make sense.

### CODE REVIEW

**Comment by tomwayson** [comment]
bah - travis ci fail. looks like I need to test this in *nix environments.

**Comment by tomwayson** [comment]
also, I'm wondering if we should drop the "Author" prompt from the default generator - it was just there as a placeholder until I could figure out something more useful to do (which this PR does). Thoughs?

**Comment by gavinr** [comment]
Works well for me! Nice work! 

The one thing I noticed is that it assumes app index 2 (`..../server/apps/2`) - is that something that should be an input? I'm ok either way just throwing it out there.

**Comment by tomwayson** [comment]
yeah, definitely need to think through the assumptions about `appDir`. Ideally, after getting the root dir, it would check for the existence of app folders, and then offer a checklist:

[ ] App 2
[ ] App 3
[ ] App 4

A few challenges though: 
- users often don't know the "id" of their apps, so would be even better if it could somehow get the name
- code is currently only set up to copy to one app, I think ideally we'd like to give the option to copy to more, but that adds complexity. I have not found a good way to have multiple dests for grunt tasks other than to have multiple targets.
- users may not have created an app already. I know my typical workflow is to start on the widgets and create the app later. Maybe that's just a documentation issue (i.e. encourage to create test app first)

Still w/ all those issues, I think we can start to move in this direction. Here's my list of things to do before merging this PR:

- [ ] get it working in Travis (and OSX?) env
- [ ] remove prompt for Author - should only touch parts of package.json that *need* to be modified (`devDependencies`)
- [ ] prompt for app id (either blank or a number) instead of hardcoding appDir to 2 and add docs encouraging creation of test app ahead of time

From there, we can create a new issue to look into a more useful prompt for the appDir(s) and tackle the above challenges.

Speaking of documentation, we should include docs on how to update the locations after running the generator.

**Comment by tomwayson** [comment]
as of now master is on the path to v2.0. For any changes/fixes to 1.x should be branched off of v1.2.0

**Comment by gavinr** [comment]
:+1:

**Pull request merged**
