### PR TITLE
Update to WebAppBuilder 1.2

### PR DESCRIPTION
**Pull request by g3r4n**
Basic update in order to make widget and theme working on WebAppbuilder 1.2

### CODE REVIEW

**Comment by tomwayson** [comment]
Thanks @g3r4n!

I've reviewed the changes to the widget template and made some comments.

I'm not really qualified to review the changes that you've made to the theme though. I see that you did not modify any specs, and the travis build still passed, so that's good, but I'd still like someone who has done custom theme work to review the changes before merging.

If you can describe in a sentence or two what you did (i.e. copied over the foldable them files from version 1.2 of the stemapp, etc), maybe @spohner, @yiweima, or @SpatialAgent would be willing to review.

cc @Jianxia

**Comment by g3r4n** [comment]
I've just copied over the panels files from version 1.2 of the stemapp.
I've update style sheets.
I've added an empty main.js file in theme in order to make it work in WAB 1.2.

**Comment by tomwayson** [comment]
Thanks @g3r4n. I guess leave the WAB version set to 1.3, but I definitely think the version should be set 0.0.1.

If no one else is available to review, I'll try downloading, running, and adding the output theme to my WAB. If It works, I'll merge.

**Comment by g3r4n** [comment]
Any update ?

**Comment by g3r4n** [comment]
So ?

**Comment by qlqllu** [comment]
`wabVersion` in widget manifest is used to declare the jimu version that the widget depends on, it should be `1.3`. Developer edition 1.2 use wab version 1.3.

**Comment by tomwayson** [comment]
Thanks for the insight @qlqllu.

@g3r4n Would you please push a follow up commit updating the version(s) to 0.0.1?

Then I will review.

**Comment by g3r4n** [comment]
i did it the 4th : https://github.com/g3r4n/generator-esri-appbuilder-js/commit/69997049a68c5997b9fb72e88973e995724d9e01

**Comment by tomwayson** [comment]
@g3r4n sorry, I missed that somehow.

I finally got a chance to download and try this, but I can't get the theme to show up in the builder. I ran the generator in the stemapp folder, and even saw a message in the WAB's command line output saying "New theme...", but when I went back to the WAB to create a new app, I did not see an icon for my new theme in the list of available themes on the left. I stopped/started the WAB, and tried w/ existing and new apps, but was never able to get it to show up in the builder.

I found a file named "list.json" in the stemapp's themes folder and updated it as follows, but that did not work either:

```json
{
  "themes": [
    "FoldableTheme",
    "TabTheme",
    "LaunchpadTheme",
    "BoxTheme",
    "BillboardTheme",
    "JewelryBoxTheme",
    "DartTheme",
    "Defaultthemename"
  ]
}
```

I checked the documentation, and didn't see any additional deployment steps besides making sure the theme is in the themes folder and starting the WAB. I did notice a few differences between [the example manifest.json](https://developers.arcgis.com/web-appbuilder/guide/create-a-theme.htm#ESRI_SECTION1_5A7C59F0EAEF4EA49722C49E92C7E793) and the manifest.json that is output by the generator. Specifically, the generated file is missing `platform` and `wabVersion`.

@g3r4n, would you please list the steps you took to get the theme you generated to show up in the builder?

**Comment by tomwayson** [comment]
It was the missing `"platform": "HTML"`, after adding that it worked.

@g3r4n can you please add that as well as `wabVersion: 1.3` to be consistent with the other themes to the _manifest.json template?

**Comment by tomwayson** [comment]
Merged. Thank you @g3r4n!

**Pull request merged**
