### PR TITLE
70 Do not scaffold jshint file

### PR DESCRIPTION
**Pull request by gavinr**
addresses #70 by removing the jshint file from being generated.

(note: branched from https://github.com/gavinr/generator-esri-appbuilder-js/tree/yeoman-generator-1.0 so please do not review/merge until #80 is merged in)

### CODE REVIEW

**Comment by tomwayson** [comment]
@gavinr w/ the merged commits, this PR and #84 are hard to review. Seems like the only novel commit in this PR is c82594b166028d44779a4c302085286292ab7c3e - do you think you could make a new PR w/ just that?

**Comment by gavinr** [comment]
I merged in master. PR should now be clean for re-review @tomwayson

**Comment by tomwayson** [comment]
I merged this, then immediately realized that the [README has to be updated](https://github.com/Esri/generator-esri-appbuilder-js/blob/master/README.md#linting-your-code). Just need to remove any references to jshint related stuff.

**Comment by tomwayson** [comment]
Maybe that can be added to #84

**Comment by gavinr** [comment]
@tomwayson good catch. will add that to #84 real quick. thanks

**Pull request merged**
